<?php
			$optionsArray = array( 'totals' => array( 'id_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'PersonaDNI_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'PersonaApellidoNombre_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'PersonaFechaNacimiento_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'PersonaCiudadReside_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'Personaemail_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'PersonaTelefonoContacto_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'PuestoTrabajoPostula_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'ConvocatoriaDifusion_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'PersonaCV_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'RegistroFechaHora_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'Titulo_iConvocatoriasProvinciales' => array( 'totalsType' => '' ),
'AniosResidencia_iConvocatoriasProvinciales' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_iConvocatoriasProvinciales',
'PersonaDNI_iConvocatoriasProvinciales',
'PersonaApellidoNombre_iConvocatoriasProvinciales',
'PersonaFechaNacimiento_iConvocatoriasProvinciales',
'PersonaCiudadReside_iConvocatoriasProvinciales',
'Personaemail_iConvocatoriasProvinciales',
'PersonaTelefonoContacto_iConvocatoriasProvinciales',
'PersonaCV_iConvocatoriasProvinciales',
'RegistroFechaHora_iConvocatoriasProvinciales',
'Titulo_iConvocatoriasProvinciales',
'AniosResidencia_iConvocatoriasProvinciales' ),
'exportFields' => array( 'id_iConvocatoriasProvinciales',
'PersonaDNI_iConvocatoriasProvinciales',
'PersonaApellidoNombre_iConvocatoriasProvinciales',
'PersonaFechaNacimiento_iConvocatoriasProvinciales',
'PersonaCiudadReside_iConvocatoriasProvinciales',
'Personaemail_iConvocatoriasProvinciales',
'PersonaTelefonoContacto_iConvocatoriasProvinciales',
'PersonaCV_iConvocatoriasProvinciales',
'RegistroFechaHora_iConvocatoriasProvinciales',
'Titulo_iConvocatoriasProvinciales',
'AniosResidencia_iConvocatoriasProvinciales' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_iConvocatoriasProvinciales' => array( 'export_field' ),
'PersonaDNI_iConvocatoriasProvinciales' => array( 'export_field1' ),
'PersonaApellidoNombre_iConvocatoriasProvinciales' => array( 'export_field2' ),
'PersonaFechaNacimiento_iConvocatoriasProvinciales' => array( 'export_field3' ),
'PersonaCiudadReside_iConvocatoriasProvinciales' => array( 'export_field4' ),
'Personaemail_iConvocatoriasProvinciales' => array( 'export_field5' ),
'PersonaTelefonoContacto_iConvocatoriasProvinciales' => array( 'export_field6' ),
'PersonaCV_iConvocatoriasProvinciales' => array( 'export_field7' ),
'RegistroFechaHora_iConvocatoriasProvinciales' => array( 'export_field8' ),
'Titulo_iConvocatoriasProvinciales' => array( 'export_field9' ),
'AniosResidencia_iConvocatoriasProvinciales' => array( 'export_field10' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'PersonaDNI_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'PersonaApellidoNombre_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'PersonaFechaNacimiento_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'PersonaCiudadReside_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Personaemail_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'PersonaTelefonoContacto_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'PersonaCV_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'RegistroFechaHora_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Titulo_iConvocatoriasProvinciales',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'AniosResidencia_iConvocatoriasProvinciales',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>