<?php
			$optionsArray = array( 'totals' => array( 'id_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'bPDF' => array( 'totalsType' => '' ),
'PersonaDNI_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'PersonaApellidoNombre_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'PersonaFechaNacimiento_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'PersonaProvinciaReside_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'Personaemail_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'PersonaTelefonoContacto_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'PuestoTrabajoPostula_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'ResidenciaCompleta_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'ResidenciaEspecialidad_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'PersonaTituloEspecialista_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'PersonaEspecialidadCertificada_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'ConvocatoriaDifusion_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'PersonaCV_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'RegistroFechaHora_iConvocatoriasNacionales' => array( 'totalsType' => '' ),
'TituloGrado_iConvocatoriasNacionales' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'PersonaDNI_iConvocatoriasNacionales',
'PersonaApellidoNombre_iConvocatoriasNacionales',
'PersonaFechaNacimiento_iConvocatoriasNacionales',
'PersonaProvinciaReside_iConvocatoriasNacionales',
'Personaemail_iConvocatoriasNacionales',
'PersonaTelefonoContacto_iConvocatoriasNacionales',
'PuestoTrabajoPostula_iConvocatoriasNacionales',
'ResidenciaCompleta_iConvocatoriasNacionales',
'ResidenciaEspecialidad_iConvocatoriasNacionales',
'PersonaTituloEspecialista_iConvocatoriasNacionales',
'PersonaEspecialidadCertificada_iConvocatoriasNacionales',
'ConvocatoriaDifusion_iConvocatoriasNacionales',
'TituloGrado_iConvocatoriasNacionales',
'RegistroFechaHora_iConvocatoriasNacionales' ),
'exportFields' => array( 'PersonaDNI_iConvocatoriasNacionales',
'PersonaApellidoNombre_iConvocatoriasNacionales',
'PersonaFechaNacimiento_iConvocatoriasNacionales',
'PersonaProvinciaReside_iConvocatoriasNacionales',
'Personaemail_iConvocatoriasNacionales',
'PersonaTelefonoContacto_iConvocatoriasNacionales',
'PuestoTrabajoPostula_iConvocatoriasNacionales',
'ResidenciaCompleta_iConvocatoriasNacionales',
'ResidenciaEspecialidad_iConvocatoriasNacionales',
'PersonaTituloEspecialista_iConvocatoriasNacionales',
'PersonaEspecialidadCertificada_iConvocatoriasNacionales',
'ConvocatoriaDifusion_iConvocatoriasNacionales',
'TituloGrado_iConvocatoriasNacionales',
'RegistroFechaHora_iConvocatoriasNacionales' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PersonaDNI_iConvocatoriasNacionales' => array( 'export_field' ),
'PersonaApellidoNombre_iConvocatoriasNacionales' => array( 'export_field1' ),
'PersonaFechaNacimiento_iConvocatoriasNacionales' => array( 'export_field2' ),
'PersonaProvinciaReside_iConvocatoriasNacionales' => array( 'export_field3' ),
'Personaemail_iConvocatoriasNacionales' => array( 'export_field4' ),
'PersonaTelefonoContacto_iConvocatoriasNacionales' => array( 'export_field5' ),
'PuestoTrabajoPostula_iConvocatoriasNacionales' => array( 'export_field6' ),
'ResidenciaCompleta_iConvocatoriasNacionales' => array( 'export_field7' ),
'ResidenciaEspecialidad_iConvocatoriasNacionales' => array( 'export_field8' ),
'PersonaTituloEspecialista_iConvocatoriasNacionales' => array( 'export_field9' ),
'PersonaEspecialidadCertificada_iConvocatoriasNacionales' => array( 'export_field10' ),
'ConvocatoriaDifusion_iConvocatoriasNacionales' => array( 'export_field11' ),
'TituloGrado_iConvocatoriasNacionales' => array( 'export_field12' ),
'RegistroFechaHora_iConvocatoriasNacionales' => array( 'export_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'PersonaDNI_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'PersonaApellidoNombre_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'PersonaFechaNacimiento_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'PersonaProvinciaReside_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Personaemail_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'PersonaTelefonoContacto_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'PuestoTrabajoPostula_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'ResidenciaCompleta_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'ResidenciaEspecialidad_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'PersonaTituloEspecialista_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'PersonaEspecialidadCertificada_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'ConvocatoriaDifusion_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'TituloGrado_iConvocatoriasNacionales',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'RegistroFechaHora_iConvocatoriasNacionales',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>