<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_ConvocatoriasNacionales_PrintPDF  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;

		$this->events["BeforeShowPrint"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$dni = $values['PersonaDNI_iConvocatoriasNacionales'];
if ($dni<1000000) 
{
	$message = "El DNI debe ser un número mayor, por favor corrobore el campo registrado.";
	return false;
}

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowPrint(&$xt, &$templatefile, $pageObject)
{

		// Código para mostrar comprobante 
require('fpdf.php');

// Mostrar el lugar y la fecha
$fecha = date('Y-m-d');
$m = date("m", strtotime($fecha)); 
$d = date("d", strtotime($fecha));
$y = date("Y", strtotime($fecha));
switch ($m)
{
	case 1:  
		{
			$mes = 'Enero';
			break;
		}
	case 2:  
		{
			$mes = 'Febrero';
			break;
		}
	case 3: 
		{
			$mes = 'Marzo';
			break;
		}
	case 4:  
		{
			$mes = 'Abril';
			break;
		}
	case 5:  
		{
			$mes = 'Mayo';
			break;
		}
	case 6: 
		{
			$mes = 'Junio';
			break;
		}
	case 7:  
		{
			$mes = 'Julio';
			break;
		}
	case 8: 
		{
			$mes = 'Agosto';
			break;
		}
	case 9:  
		{
			$mes = 'Septiembre';
			break;
		}
	case 10:
	{
		$mes = 'Octubre';	
		break;
	}
	case 11: 
		{
			$mes = 'Noviembre';
			break;
		}
	case 12: 
		{
			$mes = 'Diciembre';	
			break;
		}
	break;
}
$fecha = 'USHUAIA, '.$d. ' de '.$mes. ' de '.$y; 
$titulo = "Constancia de inscripción a convocatoria nacional";

$idPostulante = $_GET["id"];
// ************************************************************************************************************************************************************************************************************** //
// Armado de pdf
$pdf=new FPDF('P','mm','Legal');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Arial','B',10);
$pdf->Cell(0,3,$fecha,0,1,'R');
$pdf->Ln(10);
$pdf->SetFont('Arial','BU',12);
$pdf->Cell(0,8,utf8_decode($titulo),0,1,'C');
$pdf->Ln(10);
$pdf->SetFont('Arial','',12);

// Buscar los datos de los productos entregados
// Código principal - fhoras 21-06-16
global $dal;
$sql = "SELECT
					PersonaDNI_iConvocatoriasNacionales as dni,
					PersonaApellidoNombre_iConvocatoriasNacionales as apenom,
					PersonaFechaNacimiento_iConvocatoriasNacionales as fecnac,
					PersonaProvinciaReside_iConvocatoriasNacionales as provres,
					Personaemail_iConvocatoriasNacionales as email,
					PersonaTelefonoContacto_iConvocatoriasNacionales as tel,
					PuestoTrabajoPostula_iConvocatoriasNacionales as puesto,
					ResidenciaCompleta_iConvocatoriasNacionales as rescom,
					ResidenciaEspecialidad_iConvocatoriasNacionales as espe,
					PersonaTituloEspecialista_iConvocatoriasNacionales as titulo,
					PersonaEspecialidadCertificada_iConvocatoriasNacionales as insticert,
					TituloGrado_iConvocatoriasNacionales as titgrado,
					RegistroFechaHora_iConvocatoriasNacionales as registro
				FROM I_ConvocatoriasNacionales
				WHERE id_iConvocatoriasNacionales = $idPostulante";
$rs = CustomQuery($sql);
$row = db_fetch_array($rs);
$FechaNac = date("d-m-Y", strtotime($row["fecnac"]));
$Registro = date("d-m-Y", strtotime($row["registro"]));
$ApeNom = strtoupper($row["apenom"]);
$pdf->Cell(100,7,utf8_decode('DNI: '.$row["dni"]),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Apellido y Nombre: '.$ApeNom),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Fecha de nacimiento: '.$FechaNac),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Provincia reside: '.$row["provres"]),0,1,'L');
$pdf->Cell(100,7,utf8_decode('E-mail: '.$row["email"]),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Teléfono: '.$row["tel"]),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Puesto: '.$row["puesto"]),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Título de Grado: '.$row["titgrado"]),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Residencia Completa: '.$row["rescom"]),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Especialidad: '.$row["espe"]),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Título especialista: '.$row["titulo"]),0,1,'L');
$pdf->Cell(100,7,utf8_decode('Registro: '.$Registro),0,1,'L');
$pdf->Ln(20);
$pdf->Output();
// ************************************************************************************************************************************************************************************************************** //
;		
} // function BeforeShowPrint

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
