<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_Mails_para_notificar  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$values['RegistroFecha_IConvNacMailsNotif'] = date('Y-m-d');
$values['RegistroHora_IConvNacMailsNotif'] = date('H:m:s');
$values['RegistroUsr_IConvNacMailsNotif'] = $_SESSION["UserID"];
// 9 es el Sistema de Convocatorias
$values['idSistema_iConvNacMailsNotif'] = 9;
return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
