<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => '',
'active' => true,
'code' => '00',
'codeField' => '',
'emailField' => '',
'extUserIdField' => '',
'fullnameField' => 'UserName_UsuarioPermisos',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Clave_UsuariosPermisos',
'phoneField' => '',
'resetDateField' => '',
'resetTokenField' => '',
'table' => array( 'connId' => 'Mesa_Entrada_at_10_20_96_220',
'table' => 'UsuariosPermisos' ),
'twoFactorField' => '',
'userGroupField' => 'idPerfil_UsuariosPermisos',
'usernameField' => 'UserName_UsuarioPermisos',
'userpicField' => '' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'mr6bpzL0idoFYwJ7HBhx',
'JWTSecret' => 'keBgYfk4x8FtgXp0g5Ym' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'adminEmail' => '',
'caseInsensitiveLogin' => false,
'changePasswordPage' => false,
'hashPassword' => false,
'notifyAdmin' => false,
'notifyUser' => false,
'registerPage' => false,
'remindPasswordPage' => false,
'sendActivationLink' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => true,
'useBuiltInMailer' => false,
'SMTPServer' => 'localhost',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => true ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => '',
'table' => '' ),
'lockingTable' => array( 'connId' => '',
'table' => '' ),
'tables' => array(  ),
'loggingMode' => 0,
'loggingFile' => 'audit.log',
'logSecurityActions' => false,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'Convocatorias-041022v100v106',
'loginDataSource' => '',
'loginForm' => 0,
'dynamicPermissions' => false,
'dpTablePrefix' => '',
'dpTableConnId' => '',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => '',
'active' => true,
'code' => '00',
'codeField' => '',
'emailField' => '',
'extUserIdField' => '',
'fullnameField' => 'UserName_UsuarioPermisos',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Clave_UsuariosPermisos',
'phoneField' => '',
'resetDateField' => '',
'resetTokenField' => '',
'table' => array( 'connId' => 'Mesa_Entrada_at_10_20_96_220',
'table' => 'UsuariosPermisos' ),
'twoFactorField' => '',
'userGroupField' => 'idPerfil_UsuariosPermisos',
'usernameField' => 'UserName_UsuarioPermisos',
'userpicField' => '' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ) );
?>